"""
Django settings for educa project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-utma-eu^ruz$%2wa&$+hv-*=h7enk41ulihu3wk^d&h)l&gst1'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'courses.apps.CoursesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'embed_video',
    'debug_toolbar',
    'redisboard',
    'rest_framework',
    'chat.apps.ChatConfig',
    'students.apps.StudentsConfig',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'educa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'educa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

#DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = reverse_lazy('student_course_list')

# Caching configuration for the project
#CACHES = {
#   'default': {
        # Use Redis as the caching backend
#       'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#       # Redis server location (IP and port)
#       'LOCATION': 'redis://127.0.0.1:6379',
#   }
#}

# Middleware cache settings
CACHE_MIDDLEWARE_ALIAS = 'default'  # Specifies the cache alias to use
CACHE_MIDDLEWARE_SECONDS = 60 * 15  # Cache duration (15 minutes)
CACHE_MIDDLEWARE_KEY_PREFIX = 'educa'  # Prefix for cache keys to avoid conflicts

# Internal IPs for debugging tools like Django Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',  # Localhost IP
]


# Django REST framework configuration
REST_FRAMEWORK = {
    # Set the default permission classes for the API views
    'DEFAULT_PERMISSION_CLASSES': [
        # Allow read-only access for anonymous users and provide model-level
        # permissions for authenticated users
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


ASGI_APPLICATION = 'educa.asgi.application'

# Define channel layers for handling asynchronous communication
CHANNEL_LAYERS = {
    # Default channel layer configuration
    'default': {
        # Specify the backend to use for the channel layer
        # 'channels_redis' is a backend that uses Redis as the message broker
        'BACKEND': 'channels_redis.core.RedisChannelLayer',

        # Configuration settings for the Redis backend
        'CONFIG': {
            # List of Redis server hosts to connect to
            # Each host is specified as a tuple containing the IP address and port
            'hosts': [('127.0.0.1', 6379)],  # Local Redis server running on port 6379
        },
    },
}
