# Generated by Django 5.0.10 on 2025-01-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
    ]
